global using Ardalis.GuardClauses;
global using AutoMapper;
global using AutoMapper.QueryableExtensions;
global using Microsoft.EntityFrameworkCore;
global using FluentValidation;
global using FluentValidation.Results;
global using MediatR;
global using sp26se058_3dprintshop_be.Application.Common.Security;
global using sp26se058_3dprintshop_be.Application.Common.Extensions;
global using sp26se058_3dprintshop_be.Application.Common.Interfaces;
global using sp26se058_3dprintshop_be.Application.Common.Exceptions;
global using sp26se058_3dprintshop_be.Application.Common.Attributes;
global using sp26se058_3dprintshop_be.Application.Common.Mappings;
global using sp26se058_3dprintshop_be.Application.Common.Models;
global using sp26se058_3dprintshop_be.Domain.Entities;
global using ValidationException = sp26se058_3dprintshop_be.Application.Common.Exceptions.ValidationException;
